# after running the dockerbuild image,
# get laundry-opt.tar from dockerbuild container by:
# docker cp laundrybuild:/opt/laundry - > laundry-opt.tar
# then build this image like so:
# docker build -f Dockerfile.programs-runtime -t laundry-programs  .

FROM ubuntu:18.04
RUN apt update
RUN apt -y install ghostscript imagemagick
RUN useradd -m docconv
WORKDIR /home/docconv
USER docconv
