# after running the dockerbuild image,
# get laundry-opt.tar from dockerbuild container by:
# docker cp laundrybuild:/opt/laundry - > laundry-opt.tar
# then build this image like so:
# docker build -f Dockerfile.programs-runtime -t laundry-programs  .

FROM ubuntu:18.04
RUN apt update && apt -y install libgomp1 libpng16-16 libjpeg8 libomp5 && useradd -m docconv
COPY laundry-opt.tgz /laundry-opt.tgz
RUN tar -C /opt -xzf /laundry-opt.tgz
WORKDIR /home/docconv
USER docconv
