#!/usr/bin/env bash

TOOLBIN=$(dirname $0)
INPUT=$1
OUTPUT=$2

export LD_LIBRARY_PATH=$(dirname $TOOLBIN)/lib64

# todo: share (fire|ns)jail settings
firejail \
   --noprofile \
   --private \
   --read-only=/opt \
   --read-only=/usr \
   --net=none \
   --caps.drop=all \
   --shell=none \
   --env="LD_LIBRARY_PATH=$LD_LIBRARY_PATH" \
   "$TOOLBIN/sandbox-access-test.sh"


