#!/bin/sh

set -eu

TEMPFILE=$1
ALGORITHM=$2

case $ALGORITHM
in
   sha256)
      OUT=$(sha256sum "$TEMPFILE")
      echo $OUT | sed -e 's/ .*//'
      ;;
   *)
      echo wat
      exit 1
esac

exit 0
