#!/usr/bin/env bash

set -u

INPUT=$1
OUTPUT=$2
PDFVERSION=$3

docker run \
  --runtime="${LAUNDRY_DOCKER_RUNTIME:-runsc}" \
  --network=none \
  --ipc=private \
  --memory 1g \
  --cap-drop=ALL \
  -i \
  --rm \
  laundry-programs \
  /bin/bash -c 'cat > /home/docconv/document.docx && \
    mkdir -p /home/docconv/out &&  umask 077 &&      \
    soffice                                          \
    --headless                                       \
    --convert-to pdf:writer_pdf_Export:"{\"SelectPdfVersion\":{\"type\":\"long\",\"value\":'\"$PDFVERSION\"'}}" \
    --outdir /home/docconv/out                       \
    /home/docconv/document.docx > conv.out 2>&1;     \
    tar -cf - conv.out out/*; ls -la . out >> conv.out' \
  < "$INPUT" | tar --to-stdout -xf - out/document.pdf > "$OUTPUT"
