#!/usr/bin/env bash

INPUT=$1
OUTPUT=$2

docker run \
  --runtime=${LAUNDRY_DOCKER_RUNTIME:-runsc} \
  --network=none \
  --ipc=private \
  --memory 1g \
  --kernel-memory=100M \
  --cap-drop=ALL \
  -i \
  --rm \
  laundry-programs \
  /bin/bash -c '/opt/laundry/bin/gs -q -dBATCH -dNOPAUSE -dSAFER -sDEVICE=txtwrite -sOutputFile=- -' < "$INPUT" > "$OUTPUT"
