#!/usr/bin/env bash

set -e

TOOLBIN=$(dirname $0)
INPUT=$1
OUTPUT=$2

export LD_LIBRARY_PATH=$(dirname $TOOLBIN)/lib64

mkdir -p /tmp/preview

CSUM=$(sha1sum "$INPUT" | sed -e 's/ .*//')

cp "$INPUT" /tmp/preview/$CSUM.pdf

# some room for race here
test -f /tmp/preview/$CSUM.png || firejail \
   --noprofile \
   --private \
   --read-write=/tmp/preview \
   --read-only=/opt \
   --read-only=/usr \
   --net=none \
   --caps.drop=all \
   --shell=none \
   $TOOLBIN/gs -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -dGraphicsAlphaBits=4 -dTextAlphaBits=4 -sPageList=1 -sOutputFile="/tmp/preview/$CSUM.png" "/tmp/preview/$CSUM.pdf"

cp /tmp/preview/$CSUM.png "$OUTPUT"

