#!/usr/bin/env bash

TOOLBIN=$(dirname $0)
INPUT=$1
OUTPUT=$2
CACHE=/tmp/pdf2txt

mkdir -p "$CACHE"

CSUM=$(sha1sum "$INPUT" | sed -e 's/ .*//')

cp "$INPUT" "$CACHE/$CSUM.pdf"

test -f "$CACHE/$CSUM.txt" || firejail \
   --noprofile \
   --private \
   --read-write="$CACHE" \
   --read-only=/opt \
   --read-only=/usr \
   --net=none \
   --caps.drop=all \
   --shell=none \
   "$TOOLBIN/gs" -dBATCH -dNOPAUSE -dSAFER -sDEVICE=txtwrite -sOutputFile="$CACHE/$CSUM.txt" "$CACHE/$CSUM.pdf"

rm "$CACHE/$CSUM.pdf"

cp "$CACHE/$CSUM.txt" "$OUTPUT"

