#!/usr/bin/env bash

TOOLBIN=$(dirname $0)
INPUT=$1
OUTPUT=$2
CACHE=/tmp/pdf2pdfa

export LD_LIBRARY_PATH=$(dirname $TOOLBIN)/lib64

mkdir -p "$CACHE"

CSUM=$(sha1sum "$INPUT" | sed -e 's/ .*//')

cp "$INPUT" "$CACHE/$CSUM.pdf"

test -f "$CACHE/$CSUM-pdfa.pdf" || firejail \
   --noprofile \
   --private \
   --read-write="$CACHE" \
   --read-only=/opt \
   --read-only=/usr \
   --net=none \
   --caps.drop=all \
   --shell=none \
   --env="LD_LIBRARY_PATH=$LD_LIBRARY_PATH" \
   "$TOOLBIN/gs" -dPDFA -dBATCH -dNOPAUSE -sProcessColorModel=DeviceCMYK -sDEVICE=pdfwrite -sPDFACompatibilityPolicy=1 -sOutputFile="$CACHE/$CSUM-pdfa.pdf" "$CACHE/$CSUM.pdf"

rm "$CACHE/$CSUM.pdf"

cp "$CACHE/$CSUM-pdfa.pdf" "$OUTPUT"

