#!/usr/bin/env bash

set -u

INPUT=$1
OUTPUT=$2

docker run \
  --runtime="${LAUNDRY_DOCKER_RUNTIME:-runsc}" \
  --network=none \
  --ipc=private \
  --memory 1g \
  --cap-drop=ALL \
  -i \
  --rm \
  laundry-programs \
    /bin/bash -c 'cat > /home/docconv/document.pdf && \
    gs -q -dPDFA -dBATCH -dNOPAUSE -sProcessColorModel=DeviceCMYK -sDEVICE=pdfwrite -dPDFACompatibilityPolicy=1 -sOutputFile=- /home/docconv/document.pdf' \
    < "$INPUT" > "$OUTPUT"
