#!/usr/bin/env bash

set -u

INPUT=$1
OUTPUT=$2

docker run \
  --runtime="${LAUNDRY_DOCKER_RUNTIME:-runsc}" \
  --network=none \
  --ipc=private \
  --memory 1g \
  --cap-drop=ALL \
  -i \
  --rm \
  laundry-programs \
  /bin/bash -c 'gs -q -dSAFER -dBATCH -dNOPAUSE -sDEVICE=jpeg -dGraphicsAlphaBits=4 -dTextAlphaBits=4 -sPageList=1 -sOutputFile=- -' \
  < "$INPUT" > "$OUTPUT"
