#!/usr/bin/env bash

set -u

INPUT=$1
OUTPUT=$2
DPI=$3
MAXBITMAP=$4
PDFSETTINGS=$5
PDFA_CONFORMANCE=$6

if [ -z "$DPI" ]; then
  DPI=720
fi
re='^[0-9]+$'
if ! [[ $DPI =~ $re ]] ; then
  echo "error: DPI is not a number"
  exit 2
fi


if [ -n "$PDFSETTINGS" ]; then
  valid_settings=("/screen" "/ebook" "/printer" "/prepress" "/default")
  for i in "${valid_settings[@]}"
  do
    if [ "$i" = "$PDFSETTINGS" ] ; then
      found=true
    fi
  done
  if [ "$found" != true ]; then
    echo "error: Invalid PDFSETTINGS value"
    exit 2
  fi
  PDFSETTINGS="-dPDFSETTINGS=$PDFSETTINGS"
else
  PDFSETTINGS="-dPDFSETTINGS=/default"
fi

if [ -z "$MAXBITMAP" ]; then
  MAXBITMAP=0
fi
if ! [[ $MAXBITMAP =~ $re ]] ; then
  echo "error: MAXBITMAP is not a number"
  exit 2
fi

PDFA_CONFORMANCE_NUM=""
if [[ ! $PDFA_CONFORMANCE =~ $re ]] || [[ "$PDFA_CONFORMANCE" -lt 1 ]] || [[ "$PDFA_CONFORMANCE" -gt 3 ]]; then
  echo "error: PDFA_CONFORMANCE invalid - only values from 1 to 3 are allowed"
  exit 2
fi
if [ -n "$PDFA_CONFORMANCE" ] && [ "$PDFA_CONFORMANCE" -gt 1 ]; then
  # The ghostscript documentation specifies that -dPDFA parameter should only have the version value followed when using 2 or 3
  PDFA_CONFORMANCE_NUM="=$PDFA_CONFORMANCE"
fi

docker run \
  --runtime="${LAUNDRY_DOCKER_RUNTIME:-runsc}" \
  --network=none \
  --ipc=private \
  --memory 1g \
  --cap-drop=ALL \
  -i \
  --rm \
  laundry-programs \
    /bin/bash -c 'cat > /home/docconv/document.pdf && \
    gs -q -dPDFA'$PDFA_CONFORMANCE_NUM' -dBATCH -dNOPAUSE -r'$DPI' -dMaxBitmap='$MAXBITMAP' '$PDFSETTINGS' -sProcessColorModel=DeviceCMYK -sDEVICE=pdfwrite -dPDFACompatibilityPolicy=1 -sOutputFile=- /home/docconv/document.pdf' \
    < "$INPUT" > "$OUTPUT"
