#!/usr/bin/env bash

set -u

INPUT=$1
OUTPUT=$2
if [ "$CI" = "true" ]; then
  MEMORY_LIMIT=0
else
  MEMORY_LIMIT="${LAUNDRY_MEMORY_LIMIT:-1g}"
fi


docker run \
  --runtime="${LAUNDRY_DOCKER_RUNTIME:-runsc}" \
  --network=none \
  --ipc=private \
  --memory $MEMORY_LIMIT \
  --cap-drop=ALL \
  -i \
  --rm \
  laundry-programs \
  /bin/bash -c 'cat > /home/docconv/document.pdf && \
    mkdir -p /home/docconv/out &&  umask 077 &&      \
    soffice                                          \
    --headless                                       \
    --convert-to pdf:writer_pdf_Export               \
    --outdir /home/docconv/out                       \
    /home/docconv/document.pdf > conv.out 2>&1;     \
    tar -cf - conv.out out/*; ls -la . out >> conv.out' \
  < "$INPUT" | tar --to-stdout -xf - out/document.pdf > "$OUTPUT"
